const typographySheet = document.createElement('link');
typographySheet.rel = 'stylesheet';
typographySheet.href = 'typography.css';
document.head.appendChild(typographySheet);

const sharedNav = [
  ['committee.html','Committee'],['program-committee.html','Program Committee'],['call-for-papers.html','Call for Papers'],['workshops.html','Workshops'],['submission.html','Submission'],['program.html','Program'],['registration.html','Registration'],['keynotes.html','Keynotes'],['special-issues.html','Special Issues'],['venue.html','Venue'],['accommodation.html','Accommodation'],['contact.html','Contact']
];
const tracks = ['IoT sensing, monitoring, networking and routing','Big data analysis and cloud computing','Edge computing / fog computing','Smart cities, intelligent transportation and internet of vehicles','Artificial intelligence, machine learning and evolutionary computing','Social networks, multimedia and mobile computing','Blockchain and emerging research or technologies','Industry 4.0 and Industrial IoT','Control and decision making for Smart IoT or CPS','Security and privacy for Smart IoT or CPS'];
const trackHTML = `<div class="track-grid">${tracks.map(x=>`<div><p>${x}</p></div>`).join('')}</div>`;
const people = groups => groups.map(([title,list])=>`<h2>${title}</h2><div class="person-grid">${list.map(x=>{const p=x.split('|');return `<div class="person-card"><strong>${p[0]}</strong><span>${p[1]||''}</span></div>`}).join('')}</div>`).join('');
const pages = {
 committee:{title:'Organizing Committee',eyebrow:'LEADERSHIP',intro:'The researchers and organizers guiding IEEE SmartIoT 2026.',body:people([
  ['General Chairs',['Junshan Zhang|University of California Davis, USA','Haibin Yu|Shenyang Institute of Automation, China','Jamal Deen|McMaster University, Canada','Tie Qiu|Northeastern University, China']],
  ['Program Chairs',['Geyong Min|University of Exeter, UK','Nirwan Ansari|New Jersey Institute of Technology, USA','Jiangchuan Liu|Simon Fraser University, Canada','Mo Li|Hong Kong University of Science and Technology, China']],
  ['Advisory Committee',['Ness B. Shroff|The Ohio State University, USA','Jean-Luc Gaudiot|University of California Irvine, USA','Jianwei Huang|The Chinese University of Hong Kong, China','Mohammed Atiquzzaman|University of Oklahoma, USA','Dapeng Wu|City University of Hong Kong, China','Mohsen Guizani|MBZUAI, UAE','Yuanyuan Yang|Stony Brook University, USA','Xiuzhen Cheng|Shandong University, China','Victor C.M. Leung|University of British Columbia, Canada','Jiannong Cao|Hong Kong Polytechnic University, China','Weiming Shen|Huazhong University of Science and Technology, China','Qian Zhang|Hong Kong University of Science and Technology, China']],
  ['Organizing Committee Co-Chairs',['Jiayu Pan|Northeastern University, China','Hua Yu|Liaoning Internet Society, China','Liang Zhao|Shenyang Aerospace University, China','Xiaoling Zhang|Shenyang University of Technology, China']],
  ['Demo / Poster Chairs',['Lei Wang|Dalian University of Technology, China','Ranesh Naha|Queensland University of Technology, Australia']],
  ['Publication Chairs',['Ning Chen|Hong Kong University of Science and Technology, China','Weisheng Si|Western Sydney University, Australia','Wenbing Zhao|Cleveland State University, USA']],
  ['Special Issue Chairs',['Chen Chen|Xidian University, China','Salil Kanhere|The University of New South Wales, Australia','Songwei Zhang|Northeastern University, China']],
  ['Local Chairs',['Dong Li|Shenyang Institute of Automation, China','Bingxian Lu|Northeastern University, China','Qiang He|Northeastern University, China']],
  ['Publicity Chairs',['Tianyi Xu|Tianjin University, China','Jiancheng Chi|Dalian University of Technology, China','Vangalaur Alagar|Concordia University, Canada','Jia Hu|University of Exeter, UK']],
  ['Track Co-Chairs',['Yuanqiu Luo|Futurewei Technologies, USA','Bahman Javadi|Western Sydney University, Australia','Zhetao Li|Jinan University, China','Zhiming Zhao|University of Amsterdam, Netherlands','Fu Xiao|Nanjing University of Posts and Telecommunications, China','Xiqiang Zhang|China Mobile, China','Zhikui Chen|Dalian University of Technology, China','Yuto Lim|JAIST, Japan','Xiaobo Zhou|Tianjin University, China']],
  ['Conference Secretary',['Denghui Wang|Tianjin University, China']],
  ['Steering Committee',['Chonggang Wang|InterDigital, USA','Huansheng Ning|University of Science and Technology Beijing, China','Chunming Rong|University of Stavanger, Norway','Mahmoud Daneshmand|Stevens Institute of Technology, USA','Xiaobo Zhou|Tianjin University, China']]
 ])},
 'program-committee':{title:'Technical Program Committee',eyebrow:'TECHNICAL PROGRAM',intro:'The international experts supporting the SmartIoT 2026 peer-review process.',body:people([['Committee Members',['Gabriel Gomes de Oliveira|University of Campinas, Brazil','Pankaj Kumar Mishra|G. B. Pant University of Agriculture & Technology, India','Jiehan Zhou|University of Oulu, Finland','Hui Yu|University of Portsmouth, UK','Yin Zhang|UESTC, China','Lin Feng|Dalian University of Technology, China','Joel J.P.C. Rodrigues|University of Beira Interior, Portugal','Huansheng Ning|University of Science and Technology Beijing, China','Chun-Wei Tsai|National Sun Yat-sen University, Taiwan','Tie Qiu|Northeastern University, China','Mohammad Samarah|Florida Polytechnic University, USA','Emre Sümer|Baskent University, Turkey','Hyunbum Kim|UNC Wilmington, USA','Shahid Mumtaz|MIT, USA','Songtao Lu|Iowa State University, USA','Houbing Song|Embry-Riddle Aeronautical University, USA','Wenbing Zhao|Cleveland State University, USA','Sabu M. Thampi|IIITM, India','Thomas Kürner|TU Braunschweig, Germany','Vincent Nelis|CISTER, ISEP, Portugal','Paul Townend|University of Leeds, UK','Mirko Presser|Aarhus University, Denmark','Zhaolong Ning|The University of Hong Kong','Antonino Rullo|University of Calabria, Italy','Luca Davoli|University of Parma, Italy','Masud Rana|Lamar University, USA','Wei Wang|Macao Polytechnic University, China']]])},
 'call-for-papers':{title:'Call for Papers',eyebrow:'CONTRIBUTE',intro:'Original research for a smarter, safer and more connected world.',body:`<h2>About the call</h2><p>Internet of Things plays an important role in current and future information, network and communication systems. IoT is being employed across smart homes, smart cities, intelligent transportation, environmental monitoring, security systems and advanced manufacturing.</p><p>The 10th IEEE International Conference on Smart Internet of Things will be held on 21–24 August 2026 in Shenyang, China. Prospective authors are invited to submit original research that proposes new methodologies, directions and solutions.</p><h2>Topics of interest</h2>${trackHTML}<h2>Paper submission</h2><div class="notice blue">Papers must follow the IEEE format and be submitted as PDF. Main-conference submissions are now closed.</div><a class="button-primary" href="submission.html">Submission guidelines →</a><h2>Contact</h2><p>Questions about submissions: <a href="mailto:smartiot.conf@gmail.com">smartiot.conf@gmail.com</a></p>`},
 workshops:{title:'Workshops',eyebrow:'COMMUNITY PROGRAM',intro:'Focused forums exploring emerging ideas across the Internet of Things.',body:`<h2>Call for workshop proposals</h2><p>The 10th IEEE International Conference on Smart Internet of Things invites workshop proposals on any topic related to the conference theme.</p><table class="date-table"><tr><th>Milestone</th><th>Date / Place</th></tr><tr><td>Proposal deadline</td><td>10 March 2026</td></tr><tr><td>Acceptance notification</td><td>15 May 2026</td></tr><tr><td>Workshop dates</td><td>21–24 August 2026</td></tr><tr><td>Location</td><td>Shenyang, China</td></tr></table><h2>Proposal guidelines</h2><p>Proposals must be PDF, limited to two pages excluding references, and emailed to <a href="mailto:smartiot.conf@gmail.com">smartiot.conf@gmail.com</a>. Include:</p><ul class="plain-list"><li>Workshop title and acronym</li><li>Primary contact name, biography and email</li><li>Relevant keywords and a 150–200 word abstract</li><li>Expected participant count and duration (half or full day)</li><li>Organizing committee</li></ul><h2>Advertisement, budget & registration</h2><p>Organizers are responsible for scientific organization, advertising and program definition. Local arrangements provide rooms, coffee breaks and A/V equipment. For every ten registered workshop papers, the conference offers one complimentary full-conference registration.</p><h2>Accepted workshops</h2><div class="status-box"><span>⌁</span><h3>To be announced</h3><p>Accepted workshops will be published here.</p></div>`},
 submission:{title:'Submission',eyebrow:'AUTHOR INFORMATION',intro:'Guidelines and status for SmartIoT 2026 paper submissions.',body:`<h2>Submission guidelines</h2><p>All papers must be original, unpublished and not simultaneously submitted elsewhere. Submissions must include an abstract, keywords and the corresponding author’s email.</p><div class="content-card accent"><h3>Page limits</h3><ul class="plain-list"><li>Main-conference full papers: maximum 8 pages</li><li>Poster papers: maximum 2 pages</li><li>Page limits include figures, tables and references</li></ul></div><p>Papers must be prepared in the required CS format. Template files are available through the official publisher resources.</p><h2>Topics</h2>${trackHTML}<h2>Submission status</h2><div class="notice"><strong>Main-conference submissions are now closed.</strong><br>Authors of accepted papers should proceed with camera-ready preparation.</div><h2>Camera-ready papers</h2><p>Follow the final-submission instructions provided with your acceptance notification and submit the final version by 1 July 2026.</p><h2>Contact</h2><p><a href="mailto:smartiot.conf@gmail.com">smartiot.conf@gmail.com</a></p>`},
 program:{title:'Conference Program',eyebrow:'21–24 AUGUST 2026',intro:'Four days of research, exchange and connection in Shenyang.',body:`<div class="status-box"><span>◷</span><h2>Program to be announced</h2><p>The detailed technical program, session schedule and social events will be published here when confirmed.</p><a class="button-primary" href="keynotes.html">Explore keynote speakers →</a></div>`},
 registration:{title:'Registration',eyebrow:'ATTEND SMARTIOT 2026',intro:'Registration fees, payment instructions and visa information.',body:`<h2>Registration fees</h2><p>Each accepted paper requires one author registration by 8 July 2026.</p><table class="fee-table"><tr><th>Category</th><th>By 8 July</th><th>After 8 July</th></tr><tr><td>IEEE Member</td><td>700 USD / 4,800 RMB</td><td>800 USD / 5,450 RMB</td></tr><tr><td>Non-IEEE Member</td><td>800 USD / 5,450 RMB</td><td>900 USD / 6,100 RMB</td></tr><tr><td>Non-author</td><td>450 USD / 2,980 RMB</td><td>600 USD / 3,980 RMB</td></tr></table><h2>Paper and page policy</h2><ul class="plain-list"><li>Conference papers: 8 pages; poster papers: 2 pages.</li><li>Up to two extra pages may be purchased at 100 USD / 650 RMB per page.</li><li>Each paid registration covers one paper. An extra registration fee can cover one additional paper by the same first author.</li></ul><h2>Payment information</h2><div class="notice blue">Include “SmartIoT2026–Paper ID” in the bank-transfer note. Save the receipt and send the completed registration form to <a href="mailto:confservice@163.com">confservice@163.com</a>.</div><div class="content-card"><h3>RMB bank transfer</h3><p>账户名称：沈阳海尚商务会议策划有限公司<br>账号：3301008409200231492<br>开户银行：中国工商银行股份有限公司沈阳东塔支行</p></div><div class="content-card"><h3>USD bank transfer</h3><p><strong>Account:</strong> 3301009019200475503<br><strong>Name:</strong> Shenyang Haishang Business Conference Planning Co., Ltd.<br><strong>SWIFT:</strong> ICBKCNBJLNP<br><strong>Bank:</strong> Industrial and Commercial Bank of China, Liaoning Branch, Shenyang Huanggu Subbranch<br><strong>Bank address:</strong> No. 118 Kunshan Middle Road, Huanggu District, Shenyang, Liaoning, China</p><p>Please cover bank fees and include your paper ID in the reference. For PayPal, email the registration form to request a transfer.</p></div><h2>Visa invitation letter</h2><p>Email <a href="mailto:confservice@163.com">confservice@163.com</a> with the subject “IEEE SmartIoT2026 Visa Application”.</p>`},
 keynotes:{title:'Keynote Speakers',eyebrow:'DISTINGUISHED VOICES',intro:'Meet the researchers advancing communications, sensing and intelligent networks.',body:''},
 'special-issues':{title:'Journal Special Issues',eyebrow:'PUBLICATION OPPORTUNITIES',intro:'Selected papers may be invited for extended submission to leading journals.',body:`<h2>Participating journals</h2><div class="journal-list"><div><strong>IEEE Internet of Things Journal</strong><span>IEEE · SCI</span></div><div><strong>IEEE Network</strong><span>IEEE · SCI</span></div><div><strong>Sensors</strong><span>MDPI · SCI</span></div><div><strong>IEEE Transactions on Network Science and Engineering</strong><span>IEEE · SCI</span></div><div><strong>Journal of Cloud Computing</strong><span>Springer · SCI</span></div></div><div class="notice blue">Invitation and selection details will be communicated to eligible authors.</div>`},
 venue:{title:'Venue & Travel',eyebrow:'SHENYANG, CHINA',intro:'Sheraton Shenyang South City Hotel welcomes SmartIoT 2026.',body:`<h2>Conference venue</h2><div class="content-card accent"><h3>Sheraton Shenyang South City Hotel</h3><p>101-1 Shenzhong Street, Hunnan New District, Shenyang, Liaoning, China<br>沈阳新都绿城喜来登酒店，沈阳市浑南区沈中大街101-1号</p></div><h2>Getting there</h2><div class="transport-grid"><div class="content-card"><h3>By air</h3><p>Shenyang Taoxian International Airport (SHE) is about 9 km away, typically 10–15 minutes by taxi or car.</p></div><div class="content-card"><h3>By train</h3><p>Shenyang South Railway Station is about 5–6 km away, typically 10–20 minutes by taxi or car.</p></div><div class="content-card"><h3>By metro</h3><p>Take Shenyang Metro Line 2 to Shengbowuguan Station; the hotel is within walking distance.</p></div><div class="content-card"><h3>By taxi or car</h3><p>Show the Chinese address above to the driver. Complimentary on-site parking is available.</p></div></div>`},
 accommodation:{title:'Accommodation',eyebrow:'PLAN YOUR STAY',intro:'Hotel and booking information for conference participants.',body:`<div class="status-box"><span>⌂</span><h2>Accommodation details to be announced</h2><p>Conference room rates and reservation instructions will be published here once confirmed.</p><a class="button-primary" href="venue.html">View conference venue →</a></div>`},
 'news-registration-open':{title:'Registration is now open',eyebrow:'NEWS · 23 JUNE 2026',intro:'Registration for IEEE SmartIoT 2026 opened on 23 June 2026.',body:`<div class="content-card accent"><p class="news-detail-label">CONFERENCE UPDATE</p><h2>Join us in Shenyang</h2><p>Registration for IEEE SmartIoT 2026 is now open. Each accepted paper must have one author registration completed by <strong>8 July 2026</strong>.</p><p>The registration page contains author and non-author rates, extra-page information, payment instructions and visa invitation-letter guidance.</p><a class="button-primary" href="registration.html">View registration information →</a></div><div class="news-back"><a href="index.html#news">← Back to latest news</a></div>`},
 'news-author-notification':{title:'Author notifications have been sent',eyebrow:'NEWS · 20 JUNE 2026',intro:'The SmartIoT 2026 paper review and author-notification stage has been completed.',body:`<div class="content-card accent"><p class="news-detail-label">AUTHOR UPDATE</p><h2>Check your submission email</h2><p>Author notifications for IEEE SmartIoT 2026 have been sent. Corresponding authors should review the decision and instructions delivered to their registered email address.</p><p>Accepted-paper authors should prepare their camera-ready manuscript and complete submission by <strong>1 July 2026</strong>. At least one author must register by <strong>8 July 2026</strong>.</p><a class="button-primary" href="submission.html">Camera-ready information →</a><a class="button-primary secondary-button" href="registration.html">Registration details →</a></div><div class="news-back"><a href="index.html#news">← Back to latest news</a></div>`},
 'news-keynotes-announced':{title:'Keynote speakers announced',eyebrow:'NEWS · SMARTIOT 2026',intro:'Six distinguished researchers will share their perspectives at SmartIoT 2026.',body:`<div class="content-card accent"><p class="news-detail-label">PROGRAM UPDATE</p><h2>Distinguished voices at SmartIoT 2026</h2><p>We are pleased to announce the SmartIoT 2026 keynote speakers: Professor Xuemin Shen, Professor Ping Zhang, Professor Yunhao Liu, Professor Jamal Deen, Professor Weihua Zhuang and Professor Nei Kato.</p><p>Their work spans wireless communications, 5G and 6G systems, semantic communications, Internet of Things, intelligent networks, sensing and micro-/nano-electronics. Keynote titles will be published when confirmed.</p><a class="button-primary" href="keynotes.html">Meet the keynote speakers →</a></div><div class="news-back"><a href="index.html#news">← Back to latest news</a></div>`},
 contact:{title:'Contact',eyebrow:'GET IN TOUCH',intro:'We are happy to help with submissions, registration and attendance.',body:`<div class="contact-grid"><div class="contact-card"><h3>Paper submissions</h3><p>Questions about manuscripts, tracks and camera-ready papers.</p><a href="mailto:smartiot.conf@gmail.com">smartiot.conf@gmail.com</a></div><div class="contact-card"><h3>Registration & visa</h3><p>Registration forms, payments and invitation letters.</p><a href="mailto:confservice@163.com">confservice@163.com</a></div></div><h2>Official WeChat</h2><div class="content-card accent"><h3>IEEE_SmartIoT</h3><p>Follow the official account for conference updates.</p></div><h2>Conference details</h2><p>IEEE SmartIoT 2026<br>21–24 August 2026<br>Shenyang, China</p>`}
};
const speakers=[
 ['XS','Professor Xuemin Shen','University of Waterloo, Canada','Foreign Member of the Chinese Academy of Engineering; Fellow of the Royal Society of Canada and IEEE. Former President of the IEEE Communications Society, with extensive leadership in wireless communications and networking.'],
 ['PZ','Professor Ping Zhang','Beijing University of Posts and Telecommunications, China','Member of the Chinese Academy of Engineering and IEEE Fellow. His research spans 5G/6G systems, semantic communications and communication–AI convergence.'],
 ['YL','Professor Yunhao Liu','Tsinghua University, China','Member of the Chinese Academy of Sciences; ACM, IEEE and CCF Fellow. His work focuses on IoT, Industrial Internet, indoor localization, RFID and embodied-intelligence navigation.'],
 ['JD','Professor Jamal Deen','McMaster University, Canada','Foreign Member of the Chinese Academy of Sciences and IEEE Fellow. Distinguished for contributions to semiconductor devices, micro/nanoelectronics, biosensors and smart sensing.'],
 ['WZ','Professor Weihua Zhuang','University of Waterloo, Canada','Fellow of the Royal Society of Canada and IEEE. University Professor whose research advances future telecommunication network architectures, algorithms and protocols.'],
 ['NK','Professor Nei Kato','Tohoku University, Japan','Fellow of the Engineering Academy of Japan and IEEE; IEEE Communications Society Vice President and highly cited researcher in communications and intelligent networks.']
];
pages.keynotes.body=speakers.map(s=>`<article class="speaker"><div class="speaker-avatar">${s[0]}</div><div><h3>${s[1]}</h3><p class="role">${s[2]}</p><p><strong>Keynote title:</strong> To be announced</p><details><summary>Read biography</summary><p>${s[3]}</p></details></div></article>`).join('');

const key=document.body.dataset.page;
const page=pages[key];
document.title=`${page.title} · IEEE SmartIoT 2026`;
document.querySelector('#page-title').textContent=page.title;
document.querySelector('#page-eyebrow').textContent=page.eyebrow;
document.querySelector('#page-intro').textContent=page.intro;
document.querySelector('#page-content').innerHTML=page.body;
document.querySelector('#side-nav').innerHTML=sharedNav.map(([href,label])=>`<a href="${href}" class="${href===location.pathname.split('/').pop()?'active':''}">${label}</a>`).join('');
const menu=document.querySelector('.menu-toggle'),nav=document.querySelector('.main-nav');
menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',open)});
